---
- hosts: all
  become: true
  tasks:
    - name: update and install packages apache2 neofetch neovim htop
      package: # Package module uses the machine's underlying package manager so there is no need to specify it for every distro
        update_cache: yes
        name:
          - neofetch
          - neovim
          - htop
