---
- hosts: all
  become: true
  tasks:
    - name: update packages
      apt:
        update_cache: yes

    - name: install full-upgrade
      apt:
        upgrade: full

    - name: install apache2 package
      apt:
        name: apache2

    - name: install neofetch package
      apt:
        name: neofetch

    - name: install neovim package
      apt:
        name: neovim

    - name: install htop package
      apt:
        name: htop
